#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME" || return 1

echo "Init submodules"
yadm submodule update --recursive --init

